controldictAllowed={}
flowdictAllowed={}
fvschemedictAllowed={}

controldictAllowed["CFL"]=["ANY"]
controldictAllowed["Adaptive CFL flag"]=["0","1"]
controldictAllowed["Restart level"]=["ANY"]
controldictAllowed["Maximum Iterations"]=["ANY"]
controldictAllowed["Save Iterations"]=["ANY"]
controldictAllowed["Output File format"]=["vtk","tecplot"]
controldictAllowed["Output Data format"]=["ASCII","BINARY"]
controldictAllowed["Input File format"]=["vtk","tecplot"]
controldictAllowed["Input Data format"]=["ASCII","BINARY"]
controldictAllowed["Write Precision"]=["ANY"]
controldictAllowed["Purge Write"]=["ANY"]
controldictAllowed["Residual write Interval"]=["ANY"]
controldictAllowed["Tolerance"]=["ANY"]
controldictAllowed["Debug Level"]=["ANY"]

flowdictAllowed["Number of variables"]=["ANY"]
flowdictAllowed["Free Stream Density"]=["ANY"]
flowdictAllowed["Free Stream X-Speed"]=["ANY"]
flowdictAllowed["Free Stream Y-Speed"]=["ANY"]
flowdictAllowed["Free Stream Z-Speed"]=["ANY"]
flowdictAllowed["Free Stream Pressure"]=["ANY"]
flowdictAllowed["Free Stream Turbulence Intensity"]=["ANY"]
flowdictAllowed["Free Stream Viscosity Ratio"]=["ANY"]
flowdictAllowed["Free Stream Intermittency"]=["ANY"]
flowdictAllowed["Reference Viscosity"]=["ANY"]
flowdictAllowed["Viscosity law"]=["constant","sutherland_law"]
flowdictAllowed["Reference Temperature"]=["ANY"]
flowdictAllowed["Sutherland Temperature"]=["ANY"]
flowdictAllowed["Prandtl numbers"]=["ANY"]
flowdictAllowed["Specific heat ratio"]=["ANY"]
flowdictAllowed["Gas constant"]=["ANY"]

fvschemedictAllowed["Inviscid Flux Scheme"]=["van_leer","ausm","ausmP","ausmUP","slau","ldfss0","hlle","ea_ausm"]
fvschemedictAllowed["Higher Order Method"]=["none","ppm","muscl","weno","weno_NM"]
fvschemedictAllowed["Switch: Limiter - Pressure based switch"]=["ANY"]
fvschemedictAllowed["Turbulence Limiter Switch"]=["ANY"]
fvschemedictAllowed["Turbulence model"]=["ANY"]
fvschemedictAllowed["Transition model"]=["ANY"]
fvschemedictAllowed["Time Step"]=["l","g"]
fvschemedictAllowed["Time Integration Method"]=["none","RK4","RK2","TVDRK3","TVDRK2","implicit","plusgs"]
fvschemedictAllowed["Higher Order Boundary Conditions"]=["ANY"]
fvschemedictAllowed["Effective Area"]=["0","1","2"]

